[project]
name = "line-messaging-micro-service"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.8",
    "httpx>=0.28.1",
    "line-bot-sdk>=3.16.0",
    "minio>=7.2.15",
    "mutagen>=1.47.0",
    "python-multipart>=0.0.20",
    "uvicorn>=0.34.0",
]
